Arreglo del punto 7, he hecho que printee todo en la misma funcion
KingJorjai/DSA_SocialNetwork pull request #5
Opened 2024-10-11 21:57 UTC by Chernes1401

2024-10-12 08:56 UTC, KingJorjai requested changes

2024-10-13 11:16 UTC, KingJorjai commented
No entiendo cuál es el cambio, el código está igual que antes de los dos commits, no?

2024-10-30 18:53 UTC, GorkaItuarte approved these changes

2024-11-13 10:46 UTC, KingJorjai commented
No ha habido avances en este pull request. Lo cierro y elimino la rama.

2024-11-13 10:46 UTC, closed without merging